@ECHO OFF
ECHO Syncing from main to develop...
git checkout develop
ECHO Pulling from origin...
git pull origin develop
ECHO Merging from main...
git merge main
ECHO Pushing to origin...
git push origin develop
ECHO Done.
