name: "Http Info"
slug: "http-info"
description: "Devolve um json com todos os dados de request e também as variáveis de ambiente"
version: 1.0.6
url: "https://github.com/homelend-tecnologia/homeassistant-addons"
arch:
  # - armhf
  # - armv7
  - aarch64
  - amd64
  # - i386
image: "ghcr.io/homelend-tecnologia/homeassistant-addons-httpinfo-{arch}"
map:
  - share:rw
  # - media:rw
  # - homeassistant_config:rw
  # - addon_config:rw
  # - ssl:rw
  # - backup:rw
  # - addons:rw
  # - all_addon_configs:rw
  
role:
  - admin

hassio_api: true
hassio_role: admin
homeassistant_api: true
docker_api: true

panel_icon: mdi:home-assistant
panel_admin: true
panel_title: "Http Info"

#host_network: true
host_network: false
ingress: true
ingress_port: 8083
#ingress_entry: "/"

ports:
  8083/tcp: 8083

ports_description:
  8083/tcp: "Porta para acesso ao addon"

options:
  logins: []
  require_ssl: false
  customize:
    active: false
    folder: "customize"

schema:
  logins:
    - username: str
      password: str
      outro_nome: str
      inteiro: int
  require_ssl: bool
  customize:
    active: bool
    folder: str

enviroment:
  require_ssl: $require_ssl
  ATIVO: $customize.active

init: false
startup: application
boot: auto
auto_update: true
restart: always

#webui: "http://[HOST]:[PORT:8080]"
