name: "Homelend RabbitMQ"
slug: "homelend-rabbitmq"
description: "Servidor RabbitMQ como Add-On do Home Assistant"
version: 1.0.14
url: "https://github.com/homelend-tecnologia/homeassistant-addons/tree/main/RabbitMQ"
icon: icon.png
arch:
  # - armhf
  # - armv7
  - aarch64
  - amd64
  # - i386
image: "ghcr.io/homelend-tecnologia/homeassistant-addons-rabbitmq-{arch}"

# map:
#   - share:rw
#   - media:rw
#   - homeassistant_config:rw
#   - addon_config:rw
#   - ssl:rw
#   - backup:rw
#   - addons:rw
#   - all_addon_configs:rw
  
hassio_api: false
hassio_role: default
homeassistant_api: false
docker_api: false

panel_icon: mdi:home-assistant
panel_admin: false
panel_title: "RabbitMQ"

#host_network: true
host_network: false
ingress: true
ingress_port: 15672
ingress_entry: "/"

ports:
  5672/tcp: 5672
  15672/tcp: 15672
  1883/tcp: 1883

init: false
startup: application
boot: auto
restart: always
# image: "ghcr.io/homelend-tecnologia/homeassistant-addons-rabbitmq"

#webui: "http://[HOST]:[PORT:8080]"
