name: "Homelend RabbitMQ"
slug: "homelend-rabbitmq"
description: "Servidor RabbitMQ como Add-On do Home Assistant"
version: "v1.0.10" #não esquecer de atualizar a versão no arquivo .github/workflows/docker-build-rabbitmq.yaml também (e dar commit) para que o Home Assistant atualize o addon automaticamente (se estiver instalado)
url: "https://github.com/homelend-tecnologia/homeassistant-addons"
icon: icon.png
arch:
  # - armhf
  # - armv7
  - aarch64
  - amd64
  # - i386
# map:
#   - share:rw
#   - media:rw
#   - homeassistant_config:rw
#   - addon_config:rw
#   - ssl:rw
#   - backup:rw
#   - addons:rw
#   - all_addon_configs:rw
  
hassio_api: false
hassio_role: default
homeassistant_api: false
docker_api: false

panel_icon: mdi:home-assistant
panel_admin: false
panel_title: "RabbitMQ"


#host_network: true
host_network: false
ingress: true
#ingress_port: ${rabbitmq_management_port}
ingress_port: 15672
ingress_entry: "/"

schema:
  5672/tcp: int(1024, 65535)
  15672/tcp: int(1024, 65535)
  1883/tcp: int(1024, 65535)
descrition:
  5672/tcp: "Porta de comunicação AMQP (default: 5672)"
  15672/tcp: "Porta de gerenciamento do RabbitMQ (default: 15672)"
  1883/tcp: "Porta de comunicação MQTT (default: 1883)"

ports:
  5672/tcp: 5672
  15672/tcp: 15672
  1883/tcp: 1883


init: false
startup: application
boot: auto
restart: always
image: "ghcr.io/homelend-tecnologia/homeassistant-addons-rabbitmq"
#webui: "http://[HOST]:[PORT:8080]"
