name: Build .NET for ARM64

on:
  push:
    branches:
      - develop
    paths:
      - 'PocApi/**'
      - '.github/workflows/dotnet-poc-builder.yaml'

env:
  REGISTRY: ghcr.io


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        id: convert_repo_to_lower
        run: echo "LOWER_REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV


      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./PocApi
          file: ./PocApi/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.LOWER_REPO_NAME }}-arm64
