name: Build .NET for ARM64

on:
  push:
    branches:
      - develop
    paths:
      - 'PocApi/**'
      - '.github/workflows/dotnet-poc-builder.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./PocApi
          file: ./PocApi/Dockerfile
          platforms: linux/arm64
          push: false # true
          tags: pocapi:arm64
