name: Manually Triggered Workflow

env:
  REGISTRY: ghcr.io
  BUILD_ARGS: "--test"
  MONITORED_FILES: "apparmor.txt build.yaml config yaml Dockerfile data rootfs"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main","develop"]  ## Develop only for testing purposes

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    outputs:
      changed_files: ${{ steps.changed_files.outputs.all }}
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed_files
        uses: masesgroup/retrieve-changed-files@v3  ## External action - TODO: Fork this action and use the forked version

      - name: Get add-ons
        id: addons
        run: |
          declare -a addons
          for addon in $(find ./ -name "config.yaml" | cut -d'/' -f2 | sort -u); do
            addons+=("$addon")
          done
          echo "addons=${addons[@]}" >> "$GITHUB_OUTPUT"

      - name: Get changed add-ons
        id: changed_addons
        run: |
          declare -a changed_addons
          for addon in ${{ steps.addons.outputs.addons }}; do
            if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon ]]; then
              for file in ${{ env.MONITORED_FILES }}; do
                  if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon/$file ]]; then
                    if [[ ! "${changed_addons[@]}" =~ $addon ]]; then
                      changed_addons+=("\"${addon}\",");
                    fi
                  fi
              done
            fi
          done

          changed=$(echo ${changed_addons[@]} | rev | cut -c 2- | rev)
          if [[ -n ${changed} ]]; then
            echo "Changed add-ons: $changed";
            echo "changed=true" >> "$GITHUB_OUTPUT";
            echo "addons=[$changed]" >> "$GITHUB_OUTPUT";
          else
            echo "No add-on had any monitored files changed (${{ env.MONITORED_FILES }})";
          fi

  build:
    needs: init
    runs-on: ubuntu-latest
    if: needs.init.outputs.changed == 'true'
    name: Build ${{ matrix.arch }} ${{ matrix.addon }} add-on
    strategy:
      matrix:
        addon: ${{ fromJson(needs.init.outputs.changed_addons) }}
        arch: [ "aarch64", "amd64" ] ## ["aarch64", "amd64", "armhf", "armv7", "i386"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master ## External action - TODO: Fork this action and use the forked version
        with:
          path: "./${{ matrix.addon }}"

      - name: Check add-on
        id: check
        run: |
          if [[ "${{ steps.info.outputs.architectures }}" =~ ${{ matrix.arch }} ]]; then
             echo "build_arch=true" >> "$GITHUB_OUTPUT";
           else
             echo "${{ matrix.arch }} is not a valid arch for ${{ matrix.addon }}, skipping build";
          fi
          
      - name: Set build arguments
        if: steps.check.outputs.build_arch == 'true'
        run: |
          if [[ -z "${{ github.head_ref }}" ]] && [[ "${{ github.event_name }}" == "push" ]]; then
              echo "BUILD_ARGS=--docker-hub-check" >> $GITHUB_ENV;
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase variables
        id: vars
        run: |
          echo "LOWERCASE_REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "LOWERCASE_ADDON=${{ matrix.addon,, }}" >> $GITHUB_ENV

      - name: Build ${{ matrix.addon }} add-on
        if: steps.check.outputs.build_arch == 'true' && matrix.arch == 'aarch64'
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.addon }}
          file: ./${{ matrix.addon }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.LOWERCASE_REPOSITORY }}-${{ env.LOWERCASE_ADDON }}/aarch64
          platforms: linux/${{ matrix.arch }}
          build-args: ${{ env.BUILD_ARGS }}
        # run: |
        #   docker buildx build \
        #     --platform linux/${{ matrix.arch }} \
        #     --tag ${{ env.REGISTRY }}/homelend-tecnologia/homeassistant-addons-${{ matrix.addon }}/linux-${{ matrix.arch }} \
        #     --file ./${{ matrix.addon }}/Dockerfile \
        #     ./${{ matrix.addon }}

      - name: Build ${{ matrix.addon }} add-on
        if: steps.check.outputs.build_arch == 'true' && matrix.arch == 'amd64'
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.addon }}
          file: ./${{ matrix.addon }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.LOWERCASE_REPOSITORY }}-${{ env.LOWERCASE_ADDON }}/amd64
          platforms: linux/${{ matrix.arch }}
          build-args: ${{ env.BUILD_ARGS }}
